pipeline {
    agent any

    environment {
        APP_NAME = 'test-web-app'
        APP_PORT = '3000'
        DOCKER_IMAGE = "test-web-app:latest"
    }

    stages {
        stage('Build') {
            steps {
                echo "Branch: ${env.BRANCH_NAME}"
                sh 'docker build -t $DOCKER_IMAGE .'
            }
        }

        stage('Deploy (main only)') {
            when {
                branch 'main'
            }
            steps {
                script {
                    echo "Deploying $DOCKER_IMAGE to EC2 instance"
                    sh '''
                    docker stop $APP_NAME || true
                    docker rm $APP_NAME || true
                    docker run -d --name $APP_NAME -p $APP_PORT:$APP_PORT $DOCKER_IMAGE
                    '''
                }
            }
        }
    }
}